services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/upstreams_blue.conf:/etc/nginx/upstreams_blue.conf:ro
      - ./nginx/upstreams_green.conf:/etc/nginx/upstreams_green.conf:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL:-blue}  # Ensure variable is passed
    command: ["/entrypoint.sh"]
    depends_on:
      - app_blue
      - app_green
    networks:
      - app-network

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "${BLUE_PORT:-8081}:3000"
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "${GREEN_PORT:-8082}:3000"
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge